name: 'Lint and Test'

on:
  pull_request:
    branches:
      - master

jobs:
  Build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install
        run: npm install && npm install --only=dev
      - name: Lint
        run: npm run lint
      - run: npm test
        env:
          CI: true
      - uses: actions/upload-artifact@v2
        with:
          name: coverageReport
          path: coverage
